### ISSUE TITLE
Auto-Shifting Appearance based on Timeline

### ISSUE THREAD

**Issue by dscyrescotti** [dscyrescotti/SwiftTheming#39]
## Overview
It is a new preferred appearance called `dynamic` which provide functionality of automatic changing appearance based on timeline. It also includes default timeline to switch the appearance and provides the ability to override it as desired.

## API Implementation
```swift
public enum PreferredAppearance: Codable {
    /* the rest */
    case automatic
}
```

## Tasks
- [x] Research on auto-shifting behavior of system appearance
- [x] Brainstorm the best design of the API
- [x] Implement the auto-shifting appearance feature
- [ ] Add a modifier that listens auto shifting event 
- [ ] Testing the feature
- [ ] Update documentation
- [ ] Bump minor version
